[package]
name = "ktisis"
version = "0.2.0"
authors = ["chirp (github.com/chrpy)"]
repository = "https://github.com/ktisis-tools/ktisis"
edition = "2021"

[dependencies]
binread = "^2.2.0"
inflate = "^0.4.5"
phf = { version = "0.10", features = ["macros"] }